### ISSUE TITLE
What is the exact module to open?

### ISSUE THREAD

**Issue by ethanabrooks** [janestreet/ppx_let#10]
A little new to OCaml here, so pardon my ignorance. In order to access the `let%` binding what is the exact module that we need to open? I've tried
```
open Let_syntax
```
and 
```
open ppx_let
```
But I am getting `unbound module` errors for both. I think the answer to my question is somewhere in the 'Getting the right names in scope' section of the README but it is not clear to me how to translate that information into code.

Thanks!

**Comment by lpw25** [comment]
The module should come from the particular monad or applicative that you are trying to use. For example, if you are using [Async](https://github.com/janestreet/async) then you would open the module `Async.Deferred.Let_syntax` (you'd probably already have `Async` open and just open `Deferred.Let_syntax`).

**Comment by lpw25** [comment]
You might find the [OCaml discuss](https://discuss.ocaml.org/) more helpful for these kinds of "getting started" questions.

I'm going to close this issue since it isn't a bug or feature request.
