### ISSUE TITLE
Clarification: ppx_let requires doubly-nested Let_syntax module

### ISSUE THREAD

**Issue by aantron** [janestreet/ppx_let#11]
Contrary to expectations and the README, this fails:

`foo.ml`:

```ocaml
module M =
struct
  let return x = x
  let bind m ~f = f m

  module Let_syntax =
  struct
    let return = return
    let bind = bind
  end
end

let () =
  let%bind.M () = M.return () in
  M.return ()
```

`dune`:

```
(executable
 (name foo)
 (preprocess (pps ppx_let)))
```

Interaction:

```
$ dune exec ./foo.exe
File "foo.ml", lines 14-15, characters 2-13:
14 | ..let%bind.M () = M.return () in
15 |   M.return ()
Error: Unbound module M.Let_syntax.Let_syntax
```

The code generated for the `let%bind.M` is:

```ocaml
let () =
  M.Let_syntax.Let_syntax.bind (M.return ()) ~f:(fun () -> M.return ())
```

<br/>

By contrast, code like this

```ocaml
module Let_syntax = M.Let_syntax

let () =
  let%bind () = M.return () in
  M.return ()
```

generates

```ocaml
module Let_syntax = M.Let_syntax
let () = Let_syntax.bind (M.return ()) ~f:(fun () -> M.return ())
```

which is what I would expect.

<br/>

In addition, [according to the ppx_let README](https://github.com/janestreet/ppx_let#getting-the-right-names-in-scope),

> Alternatively, the extension can use values from a `Let_syntax` module other than the one in scope. If you write `%map.A.B.C` instead of `%map`, the expansion will use `A.B.C.Let_syntax.map` instead of `Let_syntax.map` (and similarly for all extension points).

I interpret this to mean that `%bind.M` should generate code that works with `M.Let_syntax.bind`. It currently appears to work only with `M.Let_syntax.Let_syntax.bind`.

<br/>

I understand the convenience of having e.g. `M.Syntax` so one can do `open M.Syntax` to bring `Let_syntax` into scope. If the intent was for downstream projects to also name the outer `M.Syntax` as `M.Let_syntax` for this purpose, and require the double-nesting convention, I think it should be documented.

<br/>

cc @anuragsoni

**Comment by lpw25** [comment]
> I understand the convenience of having e.g. M.Syntax so one can do open M.Syntax to bring Let_syntax into scope. If the intent was for downstream projects to also name the outer M.Syntax as M.Let_syntax for this purpose, and require the double-nesting convention, I think it should be documented.

That is the intention. I'll update the documentation.

Once upon a time it was not the intention, but then people got fed up of writing:
```ocaml
let%bind.Foo.Let_syntax x = ...
```
and so the behaviour was changed and now the somewhat ugly double-nesting is a requirement.

**Comment by lpw25** [comment]
I've updated the documentation internally. It should be reflected here when those changes make their way out via our release process.

**Comment by aantron** [comment]
Thanks!
