### ISSUE TITLE
Steps on [@tailcall] attribute and [@@deriving] attribute.

### ISSUE THREAD

**Issue by jhwoodyatt** [janestreet/ppx_let#5]
Hopefully, this is already known problem, and I don't have to contrive an example. Basically, if you use these attributes in source that **ppx_let** is allowed to process, then the OCaml compiler throws an Error: Attribute `deriving' was not used. (Or `tailcall` as the case may be.)

**Comment by diml** [comment]
Passing `-no-check` to the ppx rewriter should fix the issue

**Comment by jhwoodyatt** [comment]
Is that a workaround? Or is that a permanent fix?

**Comment by diml** [comment]
It's a permanent fix. The only way to enable thesr checks if when all rewriters are based on ppx_core/ppx_driver

**Comment by jhwoodyatt** [comment]
Sure. Okay, I'll try to figure out what "passing `-no-check` to the ppx rewriter" means, then let you know if that works for me.

**Comment by brendanlong** [comment]
This is probably a stupid question, but do you know how I would add that command to `ocamlfind`?

```
[blong@blong-xps13 src]$ ocamlfind ocamldep -package 'core ppx_deriving ppx_sexp_conv ppx_compare ppx_fields_conv      ppx_deriving.make ppx_sexp_message' -modules csv.ml
File "csv.ml", line 47, characters 29-37:
Error: Attribute `deriving' was not used
csv.ml:
```

Adding `-ppxopt 'ppx_deriving,-no-check'` doesn't seem to be right:

```
[blong@blong-xps13 src]$ ocamlfind ocamldep -package 'core ppx_deriving ppx_sexp_conv ppx_compare ppx_fields_conv ppx_sexp_message' -ppxopt 'ppx_deriving,-no-check' -modules csv.ml
(Invalid_argument Filename.chop_extension)
File "csv.ml", line 1:
Error: Error while running external preprocessor
Command line: /home/blong/.opam/4.04.1/lib/ppx_deriving/./ppx_deriving package:ppx_sexp_conv package:ppx_compare package:ppx_fields_conv -no-check '/tmp/camlppx68957a' '/tmp/camlppx7d84fc'

csv.ml:
```

I'm sure this is just unfamiliarity with how `ocamlfind` works but can you help?

**Comment by brendanlong** [comment]
In case anyone finds my comment above, you add it to ocamlfind like: `'ppx_sexp_message.deprecated-ppx-method,-no-check'`, so my command was:

```
 ocamlfind ocamldep -package 'core ppx_deriving ppx_sexp_conv ppx_compare ppx_fields_conv      ppx_deriving.make ppx_sexp_message' -ppxopt 'ppx_sexp_message.deprecated-ppx-method,-no-check' -modules csv.ml
```

Note that you may need multiple of these (we need a `-ppxopt` for `ppx_sexp_value`, `ppx_sexp_message`, `ppx_here`, and `ppx_custom_printf`).
