### ISSUE TITLE
Feature request: comonadic bind

### ISSUE THREAD

**Issue by strega-nil** [janestreet/ppx_let#6]
For some monads, it's useful to have "comonadic data" - my example is locations in a compiler. Sometimes, I want to have access to the location data in future computations, but most of the time, I just want it abstracted away. It'd be nice to have a way to ask for that data with a `%bind_comonadic`, or something. Currently, I have a hack, where I just return the location data always, and ignore it if I don't need it. Something like

```ocaml
let%bind tok, _ = next_token parser in
...
```

and then, when I require it,

```ocaml
type ast = {
  items: (string * function * span);
  ...
};
(* given old_ast: ast *)
let%bind name, name_sp = parse_item_name parser in
let%bind func, func_sp = parse_function_body parser in
{ ast with items = (name, func, (Spanned.union name_sp func_sp) :: ast.items }
```

if anyone has any better ideas on how to solve this, I'd also be willing to look at those. I'd also be willing to work on an implementation if this is actually a feature people would like in ppx_let.

**Comment by lpw25** [comment]
I can think of two reasonable solutions to this kind of issue. The first is to have a function with a type like:
```ocaml
val with_loc : 'a t -> ('a, Location.t) t
```
that you use to project the location when needed:
```ocaml
let%bind (x, loc) = with_loc (parse_thing ()) in
...
```
The other is to add another "bind" function that provides both the value and the location. You could do that like:
```ocaml
type 'a t
val return : 'a -> 'a t
val bind : 'a t -> ('a -> 'b t) -> 'b t
module Let_syntax : ...
module With_loc : sig
  module Let_syntax : sig
    val bind : 'a t -> (('a * Location.t) -> 'b t) -> 'b t
  end
end
```
then you can use ppx_let like this:
```ocaml
let%bind x = parse_thing () in
let%bind.With_loc (x, loc) = parse_thing () in
```
I haven't actually tested that approach -- you may need to change the definition of `With_loc.Let_syntax` a bit -- but in principle it should work fine.

I'm going to close this issue as it's not really a bug report or a specific feature request. Also sorry for the extremely slow response. We have a new system for managing issues on our GitHub repos now, so hopefully we should be much more responsive in future.
