### ISSUE TITLE
Feature request: any news about unit bind?

### ISSUE THREAD

**Issue by disteph** [janestreet/ppx_let#7]
Hi, I love this ppx, but indeed in the case of a unit bind I still prefer
```
<expr1>
>>= fun () ->
<expr2>
```
than
```
let%bind () = <expr1> in
<expr2>
```
I seem to understand that the ideal `;%bind` is not possible in the ppx framework; is it the same for any string xxx%bind that is used in infix position (which would be almost just as great for me)?

**Comment by disteph** [comment]
Thanks for your fast answer! Would you add it if I made a PR?

**Comment by yminsky** [comment]
No, the PR isn't the issue, since it's an easy enough change. As with many
syntax and language design questions, it's more about whether it should be
done rather than the difficulty of doing so.

**Comment by disteph** [comment]
Ah, I see. Well, in my view, it seems so close to the `if then else` case that I don't see why putting the bar in-between. I find the string `>>= fun () ->` long and somewhat ugly, and not really helping the intuition of what's going on : `;%bind` or `;%map` suggest to me "Ah, this is just a normal sequence, but a special one where interleaving can happen." (I'm thinking about Async), while I don't really want to think about it in terms of the functional aspect suggested by `fun`, which I'd almost rather relegate as a background implementation detail. And it's abiding by the idiom "Let syntax for variables, infix for point-free", which you described on your great blog post :-).
I'm just saying this in case this feature was sufficiently close to the bar of being deemed "a good thing to implement", that the modest opinion of an extra user can sway the decision :-)
But you have much more experience than me using ppx_let, and perhaps other reason I can't think of, so I'll respect the outcome (I may fork the lib for personal use, though).
